import type { Metadata } from "next";
import '@/styles/globals.css';

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

import { TailwindIndicator } from "@/components/providers/tailwind-indicator";
import { ThemeProvider } from "@/components/providers/theme-providers";
import TopLoader from "@/components/providers/top-loader";

import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

// Default theme
import '@splidejs/react-splide/css';


// or other themes
import '@splidejs/react-splide/css/skyblue';
import '@splidejs/react-splide/css/sea-green';


// or only core styles
import '@splidejs/react-splide/css/core';

import { NextIntlClientProvider, useMessages } from 'next-intl';

import Provider from "@/utils/Provider";

export const metadata: Metadata = {
  title: "Alisher Navoiy",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["vietnamese"] });

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default function LocaleLayout({ children, params: { locale }, }: Readonly<RootLayoutProps>) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light" />
            <TopLoader />
            <div className="min-h-screen">
              <Provider>
                <Navbar />
                {children}
              </Provider>
            </div>
            <TailwindIndicator />
            <Footer />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

